name: Build Docker image

on:
  push:

jobs:
  main:
    name: Docker
    #if: github.repository_owner == 'XboxDev'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        #image-name: [nxdk, nxdk-debug, nxdk-lto]
        image-name: [nxdk-debug]
        include:
          #- image-name: nxdk
          #  build-args: buildparams=CFLAGS=-O2 CXXFLAGS=-O2
          - image-name: nxdk-debug
            build-args: buildparams=DEBUG=y
          #- image-name: nxdk-lto
          #  build-args: buildparams=LTO=y CFLAGS=-O2 CXXFLAGS=-O2
    steps:
      - name: Clone Tree
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate timestamp
        id: timestamp
        run: echo ::set-output name=timestamp::$(date --rfc-3339=seconds --utc)
      - name: Generate tags
        id: tags
        run: |
          DOCKER_IMAGE=radwolfie/${{ matrix.image-name }}
          #TAGS="${DOCKER_IMAGE}:latest"
          #TAGS="$TAGS,${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
          TAGS="ghcr.io/${DOCKER_IMAGE}:latest"
          TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      #- name: Login to DockerHub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build --build-arg buildparams="${{ matrix.build-args }}" -t ${{ matrix.tag }} . \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.created=$(date --rfc-3339=seconds --utc)"
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    build-args: ${{ matrix.build-args }}
      #    platforms: linux/amd64,linux/386
      #    push: false #true
      #    target: ${{ matrix.image-name }}
      #    tags: ${{ steps.tags.outputs.tags }}
      #    labels: |
      #      org.opencontainers.image.revision=${{ github.sha }}
      #      org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}
      - name: Push
        run: |
          DOCKER_IMAGE=radwolfie/${{ matrix.image-name }}
          docker tag ghcr.io/radwolfie/nxdk ${DOCKER_IMAGE}:latest
          docker tag ghcr.io/radwolfie/nxdk ${DOCKER_IMAGE}:git-${GITHUB_SHA::8}
          docker push ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:git-${GITHUB_SHA::8}
