name: Build Docker image

on:
  push:
    branches: cmake-fixes-experimental

env:
    REGISTRY: ghcr.io

jobs:
  main:
    name: Docker
    if: github.repository_owner == 'RadWolfie'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        image-name: [nxdk]
    steps:
      - name: Clone Tree
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date --rfc-3339=seconds --utc)" >> $GITHUB_OUTPUT
      - name: Generate tags
        id: tags
        run: |
          DOCKER_IMAGE=radwolfie/${{ matrix.image-name }}
          TAGS="${{ env.REGISTRY }}/${DOCKER_IMAGE}:latest"
          TAGS="$TAGS,${{ env.REGISTRY }}/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
          echo "tags=${TAGS}"  >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: ${{ matrix.build-args }}
          platforms: linux/amd64,linux/386
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.timestamp }}
